
const jp={UPTREND:'🟢 上昇トレンド',UPTREND_PULLBACK:'🟡 上昇・押し目',DOWNTREND_REVERSAL_WAIT:'🟠 下降・反転待ち',DOWNTREND_REVERSAL_CONFIRMED:'🟢 下降・反転確認',DOWNTREND_CONTINUED:'🔴 下降継続',RANGE_BREAKOUT:'📈 レンジブレイク中・再上昇',RANGE_TRANSITION:'🟣 レンジ・転換',UNKNOWN:'⚪ 判定不能'};
const sg={BUY_CANDIDATE:'BUY',WATCH:'WATCH',AVOID:'AVOID',INSUFFICIENT:'データ不足'};
const buyStageLabel=x=>x?.buy_stage||x?.details?.buy_stage||(x?.signal==='BUY_CANDIDATE'?'BUY':'WATCH');
const signalTypeLabel=x=>({UPTREND_PULLBACK:'上昇トレンドの押し目',RANGE_BREAKOUT:'レンジブレイク中・再上昇',MONTHLY_BOTTOM:'大底候補',BOTTOM_REVERSAL:'下降後の反転',UPTREND:'上昇トレンドの再上昇',RANGE_TRANSITION:'レンジ・転換監視',DOWNTREND_CONTINUED:'下降継続・反転待ち',UNKNOWN:'買い条件'}[x?.signal_type||x?.details?.signal_type]||'買い条件');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtPrice=v=>{if(v==null||v==='')return '—';const n=Number(v);return Number.isFinite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:2}):String(v)};
const pct=v=>v==null?'—':Number(v).toFixed(2)+'%';
const changeClass=v=>{const n=Number(v);if(!Number.isFinite(n))return 'zero';const sign=n>0?'pos':n<0?'neg':'zero';const mag=Math.abs(n);return sign+(mag>=10?' extreme':mag>=3?' strong':'');};
const cls=v=>v==null?'':Number(v)>0?'ok':Number(v)<0?'bad':'';
const deviationClass=v=>{if(v==null||!Number.isFinite(Number(v)))return 'neutral';const n=Number(v),a=Math.abs(n);if(a<10)return 'neutral';if(a<20)return 'strong '+(n>0?'pos':'neg');return 'invert '+(n>0?'pos':'neg');};
const deviationHtml=v=>{if(v==null||!Number.isFinite(Number(v)))return '<span class="deviation neutral">—</span>';const n=Number(v);return `<span class="deviation ${deviationClass(n)}">${n>0?'+':''}${n.toFixed(1)}%</span>`;};
const deviationPairHtml=(daily,weekly)=>`<div class="deviation-pair"><div><span class="deviation-label">日足</span>${deviationHtml(daily)}</div><div><span class="deviation-label">週足</span>${deviationHtml(weekly)}</div></div>`;
const REALTIME_STORAGE_KEY='kabuScoreRealtimeQuotes';
function marketDay(v){if(!v)return null;const m=String(v).match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:null;}
function applyRealtimeToRows(){let saved=null;try{saved=JSON.parse(localStorage.getItem(REALTIME_STORAGE_KEY)||'null')}catch(_e){}if(!saved||typeof saved!=='object')return 0;const dailyDay=marketDay(window.__rankingUpdatedAt);const quotes=saved.quotes||{};let applied=0;document.querySelectorAll('[data-live-code]').forEach(row=>{const code=String(row.dataset.liveCode||'');const q=quotes[code]||quotes[`${code}.T`];if(!q)return;const qDay=marketDay(q.market_time)||marketDay(saved.market_day);if(dailyDay&&qDay&&qDay<dailyDay)return;if(dailyDay&&!qDay)return;const p=row.querySelector('.live-price'),c=row.querySelector('.live-change'),t=row.querySelector('.live-time');if(p)p.textContent=fmtPrice(q.price);if(c){c.textContent=pct(q.change_pct);c.className=`quote-change live-change ${changeClass(q.change_pct)}`;}if(t)t.textContent=q.market_time?`更新 ${String(q.market_time).replace('T',' ').slice(0,16)}`:'更新時刻不明';row.classList.add('live-updated');applied++;});if(applied){const st=document.getElementById('realtimeStatus');if(st)st.textContent=`保存済みリアルタイム値 ${applied}銘柄`;}return applied;}
const rsiClass=v=>{if(v==null||!Number.isFinite(Number(v)))return '';const n=Number(v);if(n<=30)return 'extreme-low';if(n>=70)return 'extreme-high';if(n<=40)return 'mild-low';if(n>=60)return 'mild-high';return '';};
const rsiHtml=v=>v==null||!Number.isFinite(Number(v))?'—':`<span class="rsi-value ${rsiClass(v)}">${Number(v).toFixed(1)}</span>`;
let allRanking=[];let companyMaster=[];
const selectedKey='kabu-score-selected-stocks';
const knownKey='kabu-score-known-stocks';
const customKey='kabu-score-custom-stocks';
function selectedCodes(){try{const x=JSON.parse(localStorage.getItem(selectedKey)||'null');return Array.isArray(x)?new Set(x):null}catch(e){return null}}
function knownCodes(){try{const x=JSON.parse(localStorage.getItem(knownKey)||'null');return Array.isArray(x)?new Set(x):new Set()}catch(e){return new Set()}}
function saveSelected(codes){localStorage.setItem(selectedKey,JSON.stringify([...codes]));}
function syncNewStocks(a){const current=new Set(a.map(x=>String(x.code)));const saved=selectedCodes();const hasKnown=localStorage.getItem(knownKey)!==null;if(!saved){localStorage.setItem(knownKey,JSON.stringify([...current]));return null;}if(!hasKnown){localStorage.setItem(knownKey,JSON.stringify([...current]));return saved;}const known=knownCodes();const next=new Set(saved);let changed=false;for(const code of current){if(!known.has(code)){next.add(code);known.add(code);changed=true;}}if(changed){localStorage.setItem(selectedKey,JSON.stringify([...next]));localStorage.setItem(knownKey,JSON.stringify([...known]));return next;}localStorage.setItem(knownKey,JSON.stringify([...known]));return saved;}
function renderPicker(a){const root=document.getElementById('stockPicker');if(!root)return;const saved=syncNewStocks(a);root.innerHTML=a.length?a.map(x=>{const checked=!saved||saved.has(x.code);const title=encodeURIComponent(`[株スコア削除] ${x.name||x.code} (${x.code})`);const body=encodeURIComponent(String(x.code));return `<div class="manage-row"><label class="manage-main"><input type="checkbox" class="stock-check" data-code="${esc(x.code)}" ${checked?'checked':''}><span><b>${esc(x.name||x.code)}</b><small>${esc(x.code)}</small></span></label><a class="delete-link" target="_blank" rel="noopener" href="https://github.com/concord2023/kabu-score/issues/new?title=${title}&body=${body}">削除依頼</a></div>`}).join(''):'<span class="muted">現在の分析対象はありません。</span>';root.querySelectorAll('.stock-check').forEach(el=>el.addEventListener('change',()=>{const codes=[...root.querySelectorAll('.stock-check:checked')].map(x=>x.dataset.code);localStorage.setItem(selectedKey,JSON.stringify(codes));renderRows();}));}
function normalizeSearch(v){return String(v??'').toLowerCase().replace(/[\s　・･._-]/g,'');}
let selectedCompany=null;
function showSelected(x){selectedCompany=x||null;const root=document.getElementById('selectedCompany');const link=document.getElementById('githubAddLink');const msg=document.getElementById('addMessage');if(!x){root.innerHTML='<span class="muted">まだ銘柄が選択されていません。</span>';link.classList.add('disabled-link');link.href='#';link.setAttribute('aria-disabled','true');if(msg)msg.textContent='';return;}root.innerHTML=`<div>${esc(x.name||x.code)}<span class="code">証券コード ${esc(x.code)}</span></div>`;const title=encodeURIComponent(`[株スコア追加] ${x.name||x.code} (${x.code})`);const body=encodeURIComponent(String(x.code));link.href=`https://github.com/concord2023/kabu-score/issues/new?title=${title}&body=${body}`;link.classList.remove('disabled-link');link.removeAttribute('aria-disabled');if(msg)msg.textContent=`選択中：${x.name||x.code}（${x.code}）。「この銘柄を追加」を押すと、コード入りのGitHub追加依頼を作成できます。`;}
function renderDeleteList(a){const root=document.getElementById('deleteStockList');if(!root)return;root.innerHTML=a.length?a.map(x=>`<div class="custom-item"><span>${esc(x.name||x.code)}（${esc(x.code)}）</span><a class="secondary-link" style="margin:0;padding:6px 8px;font-size:10px" target="_blank" rel="noopener" href="https://github.com/concord2023/kabu-score/issues/new?title=${encodeURIComponent(`[株スコア削除] ${x.name||x.code} (${x.code})`)}&body=${encodeURIComponent(String(x.code))}">削除依頼</a></div>`).join(''):'<span class="muted">現在の分析対象はありません。</span>';}
function renderSearch(q=''){const root=document.getElementById('searchResults');if(!root)return;const term=normalizeSearch(q);if(!term){root.innerHTML='<span class="muted">検索語を入力して「検索」を押してください。</span>';return;}const hits=companyMaster.filter(x=>normalizeSearch(x.name).includes(term)||normalizeSearch(x.code).includes(term));root.innerHTML=hits.length?hits.slice(0,50).map(x=>`<div class="search-result"><div class="search-result-main"><div class="search-result-name">${esc(x.name||x.code)}（${esc(x.code)}）</div><div class="search-result-meta">${esc(x.market||'東証')}</div></div><button type="button" class="search-add" data-code="${esc(x.code)}">選択</button></div>`).join(''):`<span class="muted">「${esc(q)}」に一致する上場銘柄がありません。</span>`;root.querySelectorAll('.search-add').forEach(b=>b.addEventListener('click',()=>{const x=companyMaster.find(v=>String(v.code)===String(b.dataset.code));showSelected(x);}));}
function pbrHtml(v){
  const n=Number(v);
  if(!Number.isFinite(n)||n<=0)return '<span class="valuation muted">—</span>';
  const cls=n<=0.5?'valuation-invert-red':n<=1?'valuation-red':'';
  return `<span class="valuation ${cls}">${n.toFixed(2)}倍</span>`;
}
function dividendHtml(v){
  const n=Number(v);
  if(!Number.isFinite(n)||n<0)return '<span class="valuation muted">—</span>';
  const cls=n>=4?'valuation-invert-green':n>=2?'valuation-green':'';
  return `<span class="valuation ${cls}">${n.toFixed(2)}%</span>`;
}

function formatUpdateTime(v){if(!v)return '更新時刻不明';const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(String(v).replace('T',' ').slice(0,16));return d.toLocaleString('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'});}function directionText(regime){return jp[regime]||'⚪ 判定不能';}function renderRows(){const a=allRanking;const saved=selectedCodes();const shown=saved?a.filter(x=>saved.has(x.code)):a;const sum={buy_candidates:shown.filter(x=>x.signal==='BUY_CANDIDATE').length,watch:shown.filter(x=>x.signal==='WATCH').length,avoid:shown.filter(x=>x.signal==='AVOID').length,insufficient:shown.filter(x=>x.signal==='INSUFFICIENT').length};document.getElementById('fresh').textContent=`表示中: ${shown.filter(x=>x.price!=null).length}/${shown.length}銘柄の価格データあり（全${a.length}銘柄）`;document.getElementById('summary').textContent=shown.length?`選択銘柄 ${shown.length}件`:'銘柄が選択されていません';document.getElementById('summary').className='summary';document.getElementById('note').textContent=`総合BUY ${sum.buy_candidates} / WATCH ${sum.watch} / AVOID ${sum.avoid} / データ不足 ${sum.insufficient}`;const updateTime=formatUpdateTime(window.__rankingUpdatedAt);document.getElementById('rows').innerHTML=shown.map(x=>{const d=x.details||{};const pf=d.per_forecast||{};let forecastPe=Number(pf.forecast_pe??d.per_forecast_pe);const forecastEps=Number(pf.forecast_eps??d.per_forecast_eps);if(!Number.isFinite(forecastPe)||forecastPe<=0){const price=Number(d.price??x.price);if(Number.isFinite(price)&&price>0&&Number.isFinite(forecastEps)&&forecastEps>0)forecastPe=price/forecastEps;}const perHtml=Number.isFinite(forecastPe)&&forecastPe>0?`<span class="forecast-per">${forecastPe.toFixed(2)}倍</span>`:'<span class="forecast-per muted">—</span>';return `<tr data-live-code="${esc(x.code)}"><td><a href="./detail.html?code=${encodeURIComponent(x.code)}"><div class="name">${esc(x.name||x.code)}</div><div class="sub">${esc(x.code)}</div><div class="quote"><span class="quote-price live-price">${fmtPrice(d.price)}</span><span class="quote-change live-change ${changeClass(d.change)}">${pct(d.change)}</span></div><span class="live-time">更新 ${updateTime}</span></a></td><td><div class="buy-type ${buyStageLabel(x)==="BUY"?"buy":""}">${esc(signalTypeLabel(x))}</div>${iconHtml(x)}${buyStageLabel(x)==="BUY接近"?`<span class="pill">BUY接近</span>`:""}</td><td class="direction-total" title="${esc(directionText(x.regime))}"><span class="direction-label">${esc(directionText(x.regime))}</span><span class="total-label ${x.signal==='BUY_CANDIDATE'?'ok':x.signal==='AVOID'?'bad':'warn'}">${sg[x.signal]||esc(x.signal||'—')}</span></td><td class="metric">${rsiHtml(d.rsi14)} / ${rsiHtml(d.rsi14_weekly)}</td><td class="metric">${perHtml}</td><td>${deviationPairHtml(d.vs25,d.weekly_vs26)}</td><td class="metric">${pbrHtml(d.pbr)}</td><td class="metric">${dividendHtml(d.dividend_yield)}</td></tr>`}).join('');applyRealtimeToRows();}

function iconClass(code){return code==='SUPPLY_BUY'||code==='SUPPLY_IMPROVING'?'supply':code==='BOTTOM_VOLUME'||code==='BOTTOM_REVERSAL'?'bottom':code.startsWith('RANGE_')?'breakout':code.startsWith('RSI_')?'rsi':code.startsWith('BB_')?'bb':code==='MONTHLY_MACD_BOTTOM'?'bottom':code==='EXTENDED'?'warn':''}
function shortSignalLabel(i){const m={SUPPLY_BUY:'需給',SUPPLY_IMPROVING:'需改善',BOTTOM_VOLUME:'底出来',BOTTOM_REVERSAL:'底反転',RANGE_BREAKOUT:'レンジ抜',RANGE_BREAKDOWN:'レンジ割',RSI_OVERSOLD:'R30',RSI_OVERBOUGHT:'R70',BB_DAILY_LOW:'日-2σ',BB_DAILY_HIGH:'日+2σ',BB_WEEKLY_LOW:'週-2σ',BB_WEEKLY_HIGH:'週+2σ',MONTHLY_MACD_BOTTOM:'月MACD',EXTENDED:'乖離'};return m[i.code]||''}function iconHtml(x){const arr=(x.signal_icons||[]).slice();if(!arr.length)return '<span class="muted">—</span>';return '<div class="icons">'+arr.map(i=>{const t=shortSignalLabel(i)||i.label||'';const title=esc(i.label||t);const text=esc(i.icon)+(t?' '+esc(t):'');return '<span class="icon '+iconClass(i.code)+'" title="'+title+'">'+text+'</span>';}).join('')+'</div>'}
function render(d){if(d.status==='initialization_required'){document.getElementById('date').textContent='最終更新: —';document.getElementById('fresh').textContent='初回更新待ち';document.getElementById('summary').textContent='初回更新待ち';document.getElementById('note').innerHTML='<div class="error">まだ日次データがありません。GitHub Actions の「Daily stock update」を1回実行してください。完了すると銘柄ごとの判定が表示されます。</div>';document.getElementById('rows').innerHTML='';renderPicker([]);return;}window.__rankingUpdatedAt=d.updated_at||null;allRanking=d.ranking||[];const updated=d.updated_at||'—';document.getElementById('date').textContent='最終更新: '+updated;document.getElementById('fresh').textContent='最終更新 '+updated;renderPicker(allRanking);renderRows();renderSearch(document.getElementById('stockSearch')?.value||'');}
async function loadCompanyMaster(){const status=document.getElementById('masterStatus');const urls=['./data/company_master.json','https://raw.githubusercontent.com/skr-works/ticker-master-japan/refs/heads/main/data/master.csv'];for(const url of urls){try{const r=await fetch(url+(url.includes('?')?'&':'?')+Date.now());if(!r.ok)continue;if(url.endsWith('.json')){const d=await r.json();companyMaster=Array.isArray(d)?d:(d.companies||[]);if(companyMaster.length){status.textContent=`上場銘柄マスター：${companyMaster.length.toLocaleString()}件`;return;}}else{const text=await r.text();const parseCsvLine=line=>{const a=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='\"'){if(quoted&&line[i+1]==='\"'){cur+='\"';i++;}else{quoted=!quoted;}}else if(ch===','&&!quoted){a.push(cur);cur='';}else{cur+=ch;}}a.push(cur);return a;};const lines=text.split(/\r?\n/).filter(Boolean);const out=[];for(let i=1;i<lines.length;i++){const row=parseCsvLine(lines[i]);const code=String(row[0]||'').trim().replace(/^\uFEFF/,'');const name=String(row[1]||'').trim();const sector=String(row[2]||'').trim();if(code&&name)out.push({code,name,sector,market:'東証'});}if(out.length){companyMaster=out;status.textContent=`上場銘柄マスター：${out.length.toLocaleString()}件（公開マスター）`;return;}}}catch(e){}}status.textContent='上場銘柄マスターを読み込めませんでした。';companyMaster=[];renderSearch('');}

document.getElementById('searchForm').addEventListener('submit',e=>{e.preventDefault();renderSearch(document.getElementById('stockSearch').value);});
document.getElementById('allBtn').addEventListener('click',()=>{const codes=new Set(allRanking.map(x=>x.code));saveSelected(codes);renderPicker(allRanking);renderRows();});document.getElementById('noneBtn').addEventListener('click',()=>{saveSelected(new Set());renderPicker(allRanking);renderRows();});
showSelected(null);
loadCompanyMaster();
function renderDailyAttention(d){const st=document.getElementById('dailyAttentionStatus'),root=document.getElementById('dailyAttentionRows');if(!st||!root)return;if(!d||d.status==='no_data'||!(d.candidates||[]).length){st.textContent=d?.errors?.length?'本日の外部情報を取得できませんでした。次回更新で再試行します。':'本日の注目データはまだありません。';root.innerHTML='<div class="section-note">Daily stock update後に自動生成されます。</div>';return;}st.textContent=`最終更新 ${formatUpdateTime(d.updated_at)}｜${d.candidates?.length||0}銘柄${d.status==='insufficient_heat'?'（基準未達は除外）':''}`;root.innerHTML=(d.candidates||[]).slice(0,5).map((x,i)=>{const sig=x.signal?((sg&&sg[x.signal])||x.signal):'—';const sources=(x.sources||[]).slice(0,3).map(v=>`<a href="${esc(v.url||'#')}" target="_blank" rel="noopener">${esc(v.name||v.type||'情報源')}</a>`).join('・');const memo=x.research_memo||{};return `<details class="search-result" style="margin:7px 0;padding:9px 10px;border:1px solid #edf0f2;border-radius:11px;background:#fbfcfd"><summary style="cursor:pointer;list-style:none"><strong>${i+1}. ${esc(x.name||x.code)}</strong>（${esc(x.code)}） <span class="muted">${esc(x.movement_type||'話題集中')}</span></summary><div class="search-result-meta" style="margin-top:7px"><strong>調査メモ：</strong>${esc(memo.summary||x.reason||'当日の外部情報で話題化')}<br><strong>なぜ選定：</strong>${esc(memo.why||x.explanation?.why_selected||'当日の話題化')}<br><strong>③ 材料分類：</strong>${esc(memo.category||x.explanation?.material_category||'投資家の話題・材料')}<br><strong>④ 確認ポイント：</strong>${esc(memo.check_point||'情報源本文で確認してください。')}<br><span class="muted">話題強度 ${esc(m.heat_score??x.heat_score??'—')}｜注目度 ${Number(x.score||0).toFixed(1)}｜情報源 ${esc((x.source_types||[]).join('・')||'—')}｜同日言及 ${esc(memo.mention_count??x.sources?.length??0)}件｜kabu-score ${esc(x.kabu_score??'—')} / ${esc(sig)}</span>${sources?'<br>'+sources:''}</div></details>`}).join('');}
fetch('./data/daily_recommendations.json?'+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(renderDailyAttention).catch(()=>renderDailyAttention(null));
fetch('./data/decision_ranking.json?'+Date.now()).then(r=>{if(!r.ok)throw Error('日次ランキングがありません');return r.json()}).then(render).catch(e=>{document.getElementById('summary').textContent='日次データ待ち';document.getElementById('note').innerHTML='<div class="error">'+esc(e.message)+'</div>'});
window.addEventListener('pageshow',()=>{setTimeout(applyRealtimeToRows,0);});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(applyRealtimeToRows,0);});

